"""Données de référence des organismes notifiés (ON) — PED 2014/68/UE.

Extrait du fichier source officiel NANDO NANDO_2014_68_EU.pdf (liste des
bodies notifiés sous la directive 2014/68/UE, export NANDO de la Commission
européenne). Chaque entrée : (numéro NANDO à 4 chiffres, nom).

Les noms multi-lignes du PDF sont tronqués à leur première ligne. Alimente le
référentiel OrganismeNotifie via flask seed et la liste déroulante
« Organisme notifié » du formulaire ATTDECR.
"""
from __future__ import annotations

# (numero, nom)
ORGANISMES_NOTIFIES: tuple[tuple[str, str], ...] = (

    ('0026', 'VINÇOTTE sa/nv'),
    ('0028', 'INSTITUTO DE SOLDADURA E'),
    ('0029', 'APRAGAZ A.S.B.L.'),
    ('0035', 'TÜV Rheinland Industrie Service'),
    ('0036', 'TÜV SÜD Industrie Service GmbH'),
    ('0045', 'TÜV NORD Systems GmbH & Co. KG'),
    ('0052', 'CUALICONTROL- ACI, S.A.'),
    ('0053', 'TÜV SÜD ATISAE, S.A.U.'),
    ('0056', 'BUREAU VERITAS INSPECCION Y'),
    ('0057', 'APAVE INSPECTION SPAIN, S.A.'),
    ('0058', 'OCA GLOBAL INSPECCIONES'),
    ('0062', 'BUREAU VERITAS SERVICES'),
    ('0066', 'TUV AUSTRIA ITALIA S.p.A.'),
    ('0082', 'APAVE'),
    ('0085', 'DVGW CERT GmbH'),
    ('0090', 'TÜV Thüringen e.V.'),
    ('0091', 'TÜV Technische Überwachung'),
    ('0094', 'LRQA Inspection Iberia, S.A.'),
    ('0099', 'AENOR CONFIA, S.A.U.'),
    ('0100', 'INAIL - DIPARTIMENTO'),
    ('0200', 'FORCE Certification A/S'),
    ('0343', 'LRQA Nederland B.V.'),
    ('0351', 'LC LUXCONTROL ASBL'),
    ('0396', 'TEKNOLOGISK INSTITUT'),
    ('0398', 'APAVE ITALIA CPM SRL'),
    ('0407', 'ISTITUTO GIORDANO S.P.A.'),
    ('0408', 'TÜV AUSTRIA GMBH'),
    ('0409', 'Kiwa Sweden AB'),
    ('0424', 'Kiwa Tarkastus Oy'),
    ('0425', 'ICIM S.P.A.'),
    ('0426', 'ITALCERT SRL'),
    ('0464', 'CENTRO DE APOIO TECNOLÓGICO À'),
    ('0474', 'RINA Services S.P.A.'),
    ('0475', 'IIS CERT Srl'),
    ('0476', 'KIWA CERMET ITALIA S.P.A.'),
    ('0477', 'Eurofins Product Testing Italy S.r.l.'),
    ('0496', 'DNV Business Assurance Italy S.r.l.'),
    ('0497', 'CSI SPA'),
    ('0525', 'LRQA Deutschland GmbH'),
    ('0531', 'TÜV SÜD Landesgesellschaft'),
    ('0575', 'DNV AS'),
    ('0598', 'SGS FIMKO OY'),
    ('0640', 'DEKRA Industrial AB'),
    ('0654', 'TUV HELLAS S.A.'),
    ('0656', 'MOODY TOTTRUP HELLAS S.A.'),
    ('0714', 'ECO - European Certifying'),
    ('0844', 'INGENIERIA Y TECNICAS DE'),
    ('0851', 'ASSOCIATION POUR LA SECURITE'),
    ('0875', 'DEKRA Industrial OY'),
    ('0876', 'INSTITUTO ELECTROTÉCNICO'),
    ('0905', 'Intertek Deutschland GmbH'),
    ('0906', 'TUV AUSTRIA HELLAS LTD'),
    ('0933', 'BUREAU VERITAS RINAVE'),
    ('0948', 'TUV ITALIA SRL'),
    ('1006', 'INSTITUTO TECNOLÓGICO DO GÁS'),
    ('1008', 'TÜV Rheinland InterCert Muszaki'),
    ('1015', 'STROJIRENSKY ZKUSEBNI USTAV s.p.'),
    ('1017', 'TÜV SÜD Czech s. r. o.'),
    ('1023', 'INSTITUT PRO TESTOVÁNI A'),
    ('1027', 'TÜV RHEINLAND IBERICA'),
    ('1029', 'SGS/INTERNATIONAL'),
    ('1035', 'BUREAU VERITAS IBERIA, S.L.'),
    ('1073', 'Danish Technological Institute'),
    ('1080', 'MATERIALPRÜFUNGSANSTALT'),
    ('1095', 'EUROPEAN TECHNOLOGICAL'),
    ('1117', 'Bureau Veritas Inspection and'),
    ('1128', 'European Inspection and'),
    ('1131', 'CEC - CONSORZIO EUROPEO'),
    ('1155', 'SGS Portugal - Sociedade Geral de'),
    ('1179', 'SGS – Statutory Services Belgium'),
    ('1182', 'GSI - Gesellschaft für'),
    ('1214', 'TECNO SRL'),
    ('1221', 'TÜV NORD Czech, s.r.o.'),
    ('1231', 'TÜV NORD NEDERLAND B.V.'),
    ('1242', 'ENERGIE CONSULT HOLLAND B.V.'),
    ('1250', 'Schweizerische Vereinigung für'),
    ('1253', 'Swiss Safety Center AG'),
    ('1299', 'Technicky skusobny ustav Piestany'),
    ('1306', 'ITS CONTROLLI TECNICI S.p.A.'),
    ('1325', 'AS Kiwa Latvia'),
    ('1336', 'KIWA Estonia OÜ'),
    ('1348', 'SERVICIOS DE CONTROL E'),
    ('1353', 'TÜV SÜD SLOVAKIA s.r.o.'),
    ('1354', 'Technicka inspekcia a.s.'),
    ('1370', 'BUREAU VERITAS ITALIA S.P.A.'),
    ('1381', 'SGS ICS ITALIA S.R.L.'),
    ('1407', 'UNION OF TECHNICAL SAFETY'),
    ('1417', 'ÉMI-TÜV SÜD MINŐSÉGÜGYI ÉS'),
    ('1433', 'URZAD DOZORU TECHNICZNEGO'),
    ('1450', 'INSTYTUT NAFTY I GAZU'),
    ('1462', 'CENTRALNY OSRODEK'),
    ('1463', 'POLSKI REJESTR STATKOW S.A.'),
    ('1468', 'TRANSPORTOWY DOZOR'),
    ('1526', 'TÜV Eesti OÜ'),
    ('1544', 'QUALIFORM a.s.'),
    ('1617', 'QMSCERT AUDITS-INSPECTIONS'),
    ('1637', 'SGS-TÜV Saar GmbH'),
    ('1639', 'SGS Belgium NV'),
    ('1640', 'Kiwa Assurance B.V.'),
    ('1697', 'LLC BUREAU VERITAS LATVIA'),
    ('1735', 'TÜV AUSTRIA CZECH spol.s. r.o.'),
    ('1767', 'SGS Inspecciones Reglamentarias, S.'),
    ('1783', 'TURKISH STANDARDS INSTITUTION'),
    ('1785', 'TÜRK LOYDU UYGUNLUK'),
    ('1837', 'ITEM CONSULT Ltd. - Departament'),
    ('1839', 'Velmar Certification" Ltd.'),
    ('1853', 'TÜV Rheinland Bulgaria Ltd.'),
    ('1872', 'EUCER SRL'),
    ('1878', 'VERICERT SRL'),
    ('1935', 'GENERAL APPLICATIONS OF'),
    ('1936', 'TUV Rheinland Italia SRL'),
    ('1977', 'MULTITEST" Ltd.'),
    ('1984', 'Kiwa Belgelendirme Hizmetleri A.Ş.'),
    ('2005', 'E.I.C. Engineering inspection'),
    ('2028', 'SC RINA SIMTEX - ORGANISMUL DE'),
    ('2042', 'Institut za varilstvo d.o.o.'),
    ('2052', 'UL International Italia S.r.l.'),
    ('2077', 'TAM HELLAS Certification and'),
    ('2099', 'DNV DENMARK A/S'),
    ('2102', 'TAM CERT Magyarország Vizsgáló'),
    ('2159', 'S&Q Mart Kalite Güvenlik Sanayi ve'),
    ('2195', 'Szutest Uygunluk Değerlendirme A.'),
    ('2198', 'KR HELLAS LTD.'),
    ('2221', 'SWISS APPROVAL TECHNISCHE'),
    ('2261', 'TUV CYPRUS LTD'),
    ('2266', 'DEKRA Automobil GmbH'),
    ('2268', "UAB 'Kiwa Inspecta'"),
    ('2274', 'TUV NORD Polska Sp. z o.o'),
    ('2295', 'BUREAU VERITAS SRL'),
    ('2338', 'Nortest Cyprus LTD'),
    ('2342', 'Quality Italia S.r.l.'),
    ('2354', 'TÜV NORD Turkey Teknik Kontrol'),
    ('2359', 'Dansk Trykinspektion ApS'),
    ('2360', 'PROBO Muayene ve Belgelendirme'),
    ('2375', 'OCA INSTITUTO DE CERTIFICACION,'),
    ('2378', 'TESYDO, s. r. o.'),
    ('2388', 'DNV Business Assurance B.V.'),
    ('2399', 'C&P Srl'),
    ('2408', 'PRVÁ ZVÁRAČSKÁ, a.s.'),
    ('2410', 'WPI SOLE SHAREHOLDER Ltd'),
    ('2413', '“Controltest” Ltd'),
    ('2414', 'SC TUV AUSTRIA ROMANIA SRL'),
    ('2417', 'SYNERGYCERT S.A.'),
    ('2421', 'ERGOCERT HELLAS INSPECTIONS'),
    ('2435', 'LL-C (Certification) Czech Republic'),
    ('2459', 'Inspecco Belgelendirme ve Gözetim'),
    ('2464', 'TÜV NORD Adriatic d.o.o.'),
    ('2473', 'TPK - Zavod za energetsku i'),
    ('2489', 'Hrvatski registar brodova'),
    ('2514', 'EQS CERT - UNIPESSOAL, LDA'),
    ('2515', 'SteelCERT GmbH'),
    ('2518', 'CERTIFICATION CENTER LTD'),
    ('2519', 'BUREAU VERITAS HELLAS SOLE'),
    ('2526', 'ECM Irányítási Rendszerek Európai'),
    ('2527', 'TÜV SÜD Polska Sp. z o.o.'),
    ('2529', 'TÜV NORD Scandinavia AB'),
    ('2530', '3D Incerta Belgelendirme'),
    ('2545', 'Tarkes Inspection Oy'),
    ('2558', 'Compania Nationala pentru'),
    ('2570', 'DOM-ZO 13, s.r.o.,'),
    ('2577', 'DEKRA Testing and Certification S.r.'),
    ('2580', 'TÜV NORD ITALIA S.R.L.'),
    ('2613', 'TUV NORD Bulgarien Ltd'),
    ('2619', 'Ltd. TEHNISKAIS CENTRS'),
    ('2620', 'International Weld S.r.l.'),
    ('2624', 'Certing S.r.l.'),
    ('2627', 'TUV Rheinland Polska Sp. z o.o.'),
    ('2630', 'incert technical inspections-audits'),
    ('2654', 'Dovre Sertifisering AS'),
    ('2672', 'MAGYAR HEGESZTÉSTECHNIKAI ÉS'),
    ('2674', 'FQC Standard Uygunluk'),
    ('2675', 'Enefit Solutions AS'),
    ('2680', 'Bureau Technical Inspection OÜ'),
    ('2725', 'INTERTEK INDUSTRY SERVICES'),
    ('2735', 'NORDISK SVEJSE KONTROL A/S'),
    ('2737', 'TÜV AUSTRIA TURK'),
    ('2743', 'Elme TKS OÜ'),
    ('2749', 'VBG CERT OOD'),
    ('2761', 'ITEC - ISTITUTO TECNOLOGICO'),
    ('2780', 'Norsk Energi Kontroll AS'),
    ('2781', 'TÜV AUSTRIA IBERIA - INSPECTION'),
    ('2785', 'INSPECCIONS TECNIQUES DE'),
    ('2791', 'İntertek Kalite Servisleri Ltd.Şti'),
    ('2797', 'BSI Group The Netherlands B.V.'),
    ('2798', 'Algemene certificaten voor'),
    ('2810', 'HPi Verification Services (Ireland)'),
    ('2820', 'Vertigo Inspection (ROI) Ltd t/a'),
    ('2828', 'CAC Conformity Assessment Center'),
    ('2833', 'Hartford Steam Boiler Ireland Ltd'),
    ('2837', 'Norsk Kontroll AS'),
    ('2850', 'Association of Estonian Welders'),
    ('2861', 'Ltd CE-Test'),
    ('2870', 'Bruun Inspektion'),
    ('2872', 'Technical Certification Center OÜ'),
    ('2880', 'Arrowhead Industrial Services (EU),'),
    ('2912', 'United Registrar of Systems Czech s.'),
    ('2916', 'Applus Netherlands B.V.'),
    ('2932', 'Limited liability company European'),
    ('2941', 'VERIFICATORI ASSOCIATI ITALIANI'),
    ('2942', 'Areas Certificazioni S.r.l.'),
    ('2956', 'UAB Euromatas'),
    ('2957', 'Intercert Global Sp. z o.o.'),
    ('2961', 'S.T.S. CERTIFICAZIONI S.r.l.'),
    ('2964', 'TIQUADRO CERT S.r.l.'),
    ('2966', 'TÜV SÜD Teknik Güvenlik ve Kalite'),
    ('2967', 'Eksen Belgelendirme Teknik'),
    ('2970', 'CG Nordic AB'),
    ('2984', 'EU-Cert Sp. z o.o.'),
    ('2986', 'Finspection Oy'),
    ('3028', 'BUREAU VERITAS MAGYARORSZÁG'),
    ('3041', 'DYOMEDICA CND SRL'),
    ('3051', 'UAB DEKRA Industrial'),
    ('3053', 'OCA GLOBAL ROMÂNIA SRL'),
    ('3069', 'ICI4YOU B.V.'),
    ('3075', 'Insperla Test Gözetim ve'),
    ('3077', 'ENGINYERIA DE SOLDADURA'),
    ('3086', 'Akkuyutsrst İnşaat ve Test'),
    ('3099', 'İstanbul Teknik Kontrol Eğitim'),
    ('3108', 'HMS Sp. z o.o.'),
    ('3112', 'Experte Teknik Kontrol ve'),
    ('3116', 'Inspekt Sweden AB'),
    ('3201', 'WELDADVICE CERT'),
    ('3224', 'IPEC Inspection Ltd'),
)
