"""initial schema: users, affaires, formulaires, signatures, audit

Revision ID: 6d7f9b70296a
Revises: 
Create Date: 2026-05-12 21:49:41.216348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d7f9b70296a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulaires_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('chapitre', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', name='chapitre', native_enum=False), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('libelle_en', sa.String(length=255), nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_template_code_version')
    )
    with op.batch_alter_table('formulaires_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formulaires_templates_code'), ['code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('nom', sa.String(length=120), nullable=False),
    sa.Column('prenom', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('LECTEUR', 'REDACTEUR', 'VERIFICATEUR', 'APPROBATEUR', 'ADMIN', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('affaires',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero_affaire', sa.String(length=20), nullable=True),
    sa.Column('annee', sa.Integer(), nullable=True),
    sa.Column('client_nom', sa.String(length=255), nullable=True),
    sa.Column('references_client', sa.String(length=100), nullable=True),
    sa.Column('references_internes', sa.String(length=100), nullable=True),
    sa.Column('repere', sa.String(length=100), nullable=True),
    sa.Column('type_echangeur', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.Integer(), nullable=True),
    sa.Column('annee_construction', sa.Integer(), nullable=True),
    sa.Column('statut', sa.Enum('WIZARD_BROUILLON', 'BROUILLON', 'SOUMIS', 'REJETE', 'VALIDE', 'SIGNE', 'CLOTUREE', 'ARCHIVEE', name='statut', native_enum=False, length=20), nullable=False),
    sa.Column('statut_wizard', sa.Enum('Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', name='statut_wizard', native_enum=False, length=4), nullable=True),
    sa.Column('cree_par_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cree_par_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affaires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affaires_annee'), ['annee'], unique=False)
        batch_op.create_index(batch_op.f('ix_affaires_cree_par_id'), ['cree_par_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_affaires_numero_affaire'), ['numero_affaire'], unique=True)
        batch_op.create_index(batch_op.f('ix_affaires_statut'), ['statut'], unique=False)

    op.create_table('audit_trail',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('contexte', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_trail_user_id'), ['user_id'], unique=False)

    op.create_table('formulaires',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('affaire_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('chapitre', sa.Enum('A', 'B', 'C', 'D', 'E', 'F', 'G', name='chapitre', native_enum=False), nullable=False),
    sa.Column('statut', sa.Enum('WIZARD_BROUILLON', 'BROUILLON', 'SOUMIS', 'REJETE', 'VALIDE', 'SIGNE', 'CLOTUREE', 'ARCHIVEE', name='statut', native_enum=False, length=20), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['affaire_id'], ['affaires.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code', 'template_version'], ['formulaires_templates.code', 'formulaires_templates.version'], name='fk_formulaire_template', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('affaire_id', 'code', name='uq_formulaire_affaire_code')
    )
    with op.batch_alter_table('formulaires', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formulaires_affaire_id'), ['affaire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_formulaires_chapitre'), ['chapitre'], unique=False)
        batch_op.create_index(batch_op.f('ix_formulaires_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_formulaires_statut'), ['statut'], unique=False)

    op.create_table('parametrages_affaire',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('affaire_id', sa.Integer(), nullable=False),
    sa.Column('reponses', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['affaire_id'], ['affaires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parametrages_affaire', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parametrages_affaire_affaire_id'), ['affaire_id'], unique=True)

    op.create_table('signatures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formulaire_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['formulaire_id'], ['formulaires.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signatures_formulaire_id'), ['formulaire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signatures_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###

    # ── Trigger PostgreSQL : bloque UPDATE/DELETE sur audit_trail (immuabilité) ──
    # Défense en profondeur — complète les listeners SQLAlchemy côté ORM.
    # Skippé sur SQLite (pas de support PL/pgSQL).
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("""
            CREATE OR REPLACE FUNCTION audit_trail_block_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit_trail est insert-only — % interdit', TG_OP;
            END;
            $$ LANGUAGE plpgsql;
        """)
        op.execute("""
            CREATE TRIGGER audit_trail_no_update
            BEFORE UPDATE ON audit_trail
            FOR EACH ROW EXECUTE FUNCTION audit_trail_block_mutation();
        """)
        op.execute("""
            CREATE TRIGGER audit_trail_no_delete
            BEFORE DELETE ON audit_trail
            FOR EACH ROW EXECUTE FUNCTION audit_trail_block_mutation();
        """)


def downgrade():
    # ── Drop des triggers PostgreSQL avant de drop la table ─────────────
    if op.get_bind().dialect.name == 'postgresql':
        op.execute("DROP TRIGGER IF EXISTS audit_trail_no_delete ON audit_trail;")
        op.execute("DROP TRIGGER IF EXISTS audit_trail_no_update ON audit_trail;")
        op.execute("DROP FUNCTION IF EXISTS audit_trail_block_mutation();")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signatures_user_id'))
        batch_op.drop_index(batch_op.f('ix_signatures_formulaire_id'))

    op.drop_table('signatures')
    with op.batch_alter_table('parametrages_affaire', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parametrages_affaire_affaire_id'))

    op.drop_table('parametrages_affaire')
    with op.batch_alter_table('formulaires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formulaires_statut'))
        batch_op.drop_index(batch_op.f('ix_formulaires_code'))
        batch_op.drop_index(batch_op.f('ix_formulaires_chapitre'))
        batch_op.drop_index(batch_op.f('ix_formulaires_affaire_id'))

    op.drop_table('formulaires')
    with op.batch_alter_table('audit_trail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_trail_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_trail_action'))
        batch_op.drop_index('ix_audit_entity')

    op.drop_table('audit_trail')
    with op.batch_alter_table('affaires', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affaires_statut'))
        batch_op.drop_index(batch_op.f('ix_affaires_numero_affaire'))
        batch_op.drop_index(batch_op.f('ix_affaires_cree_par_id'))
        batch_op.drop_index(batch_op.f('ix_affaires_annee'))

    op.drop_table('affaires')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('formulaires_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formulaires_templates_code'))

    op.drop_table('formulaires_templates')
    # ### end Alembic commands ###
